# these are the sequences ChatGPT gave Kevin McKernan:
R1 := AAGTCGGAGGCCAAGCGGTTCAGCAGGAATGCCGAGACCGAGT
R2 := AAGTCGGAGGCCAAGCGGTTTCAGCAGGAATGCCGAGACCGAGT
# and these are what it gave me:
P7 := AGATCGGAAGAGCACACGTCTGAACTCCAGTCA
P5 := AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT
